[LOCAL]
spark.app.name = AstroSight
spark.master = local[2]
spark.sql.extensions = org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.AstroSight = org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.AstroSight.catalog-impl = org.apache.iceberg.rest.RESTCatalog
spark.sql.catalog.AstroSight.uri = http://astrosight-iceberg-rest:8181
spark.sql.catalog.AstroSight.warehouse = /project/Warehouse
spark.driver.memory = 512m
spark.executor.memory = 512m
spark.sql.session.timeZone = Asia/Kolkata

[AWS]
spark.app.name = AstroSight
spark.sql.extensions = org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.AstroSight = org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.AstroSight.catalog-impl = org.apache.iceberg.aws.glue.GlueCatalog
spark.sql.catalog.AstroSight.io-impl = org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.AstroSight.warehouse = s3://astrosight-data/warehouse
spark.sql.catalog.AstroSight.glue.region = ap-south-1
spark.driver.memory = 512m
spark.executor.memory = 512m
spark.sql.session.timeZone = Asia/Kolkata